services:

  direct:
    image: gcr.io/hdl-containers/sim/osvb
    volumes:
      - ./src/:/src/:ro # Infrastructure location
    working_dir : /code/rundir
    env_file    : ./src/.env
    command     : /bin/sh -c "pytest -s -o cache_dir=/rundir/harness/.cache /src/test_runner.py -s"